config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root to: 'pages#home'

  resources :cookies do
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookie.rb
class Cookie < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cookies/index.html.erb
<h1>Our Cookies</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bakery Bomb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="Home" class="block">
  <h2>The Bakery Bomb</h2>
<!--   <div class="popups">
    <span class="show-popup" data-popup="first-popup">Original Bomb</span>
    <span class="show-popup" data-popup="second-popup">Midnight Bomb</span>
  </div>

  <div class="buttons-effects">
    <button class="buttons-effect from-left">
      <span></span>
      <span data-scroll="About-us">About Us</span>
    </button>
  </div> -->
</div>

<!-- <div id="About-us" class="block">
  <h2>About Us</h2>
</div>

<button class="scroll-to-top">up</button>

<div class="popup first-popup">
  <div class="inner">
    <h3>The Original Cookie Bomb</h3>
    <p>The original, chocolate chip cookie bomb.</p>
    <button class="close">close</button>
  </div>
</div>
<div class="popup second-popup">
  <div class="inner">
    <h3>The Midnight Bomb</h3>
    <p>Cocoa dough loaded with milk chocolate chips.</p>
    <button class="close">close</button>
  </div>
</div>
 -->

app/views/shared/_navbar.html.erb
<ul class="navbar">
  <%= link_to "Home", root_path, class: "linked", :"data-scroll" => "Home"%>
  <%= link_to "Our Cookies", cookies_path, class: "linked" %>
  <%= link_to "Place An Order", root_path, class: "linked" %>
  <li><a href="#" data-scroll="About-us">About Us</a></li>
</ul>

<%= content_for :after_js do %>
  <%= javascript_tag do %>
  document.app.navbar();
  <% end %>
<% end %>